[package]
name = "zero-to-llm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
dfdx = { version = "0.13.0", features = ["cuda"] }
tokenizers = "0.15.0"
